### ISSUE TITLE
define_urban CHWplacement package installation

### ISSUE THREAD

**Issue by ffeerriiss** [PATH-Global-Health/MNTD-tech-docs#13]
@ht1212 The post looks great! I'm using the function--thank you! One thing I wanted to note was it might be nice to include the install instructions `devtools::install_github("SwissTPH/CHWplacement")`, for those aren't familiar with packages on GitHub, and cite them.

**Comment by justinmillar** [comment]
Yeah, it turns out that since we made our own version of `define_urban()` that is now a part of PATHtools, I don't think CHWplacement is actually used. However, I am working with Clara to see if our function should be added to CHWplacement. So we could remove this package and add it back along with the install instructions if/when the function gets added to CHWplacement.
